#!/usr/bin/env python3
"""Stage the XHTTP runtime from the GPLv3 reference APK into a decoded base APK.

This utility performs static file selection only. It never executes code from either
APK. The selected class graph is copied to smali_classes3 so apktool can rebuild a
multidex base with the reference XHTTP runtime isolated from the existing app code.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from collections import deque
from pathlib import Path

CLASS_REF = re.compile(r"L([A-Za-z0-9_$/]+);")
CORE_PREFIX = "Lcom/dragonssh/xhttpdemo/core/"


def class_map(decoded_root: Path) -> dict[str, Path]:
    result: dict[str, Path] = {}
    for tree in decoded_root.glob("smali*"):
        if not tree.is_dir():
            continue
        for source in tree.rglob("*.smali"):
            descriptor = "L" + source.relative_to(tree).with_suffix("").as_posix() + ";"
            result[descriptor] = source
    return result


def referenced_classes(source: Path) -> set[str]:
    return {f"L{match.group(1)};" for match in CLASS_REF.finditer(source.read_text(encoding="utf-8"))}


def compute_closure(reference: dict[str, Path], base: dict[str, Path]) -> list[str]:
    queue: deque[str] = deque(sorted(name for name in reference if name.startswith(CORE_PREFIX)))
    selected: set[str] = set()

    while queue:
        descriptor = queue.popleft()
        if descriptor in selected or descriptor in base:
            continue
        source = reference.get(descriptor)
        if source is None:
            continue
        selected.add(descriptor)
        for dependency in referenced_classes(source):
            if dependency in reference and dependency not in base and dependency not in selected:
                queue.append(dependency)

    return sorted(selected)


def copy_classes(selected: list[str], reference: dict[str, Path], destination: Path) -> None:
    if destination.exists():
        shutil.rmtree(destination)
    destination.mkdir(parents=True, exist_ok=True)

    for descriptor in selected:
        relative = Path(descriptor[1:-1] + ".smali")
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(reference[descriptor], target)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference", type=Path, required=True, help="Decoded reference APK root")
    parser.add_argument("--base", type=Path, required=True, help="Decoded base APK root")
    parser.add_argument("--report", type=Path, required=True, help="JSON output with the selected class graph")
    args = parser.parse_args()

    stage = args.base / "smali_classes3"
    # The staging tree is generated by this script. Remove a previous run before
    # calculating the base class map so its copied classes are not treated as
    # pre-existing base dependencies.
    if stage.exists():
        shutil.rmtree(stage)

    reference = class_map(args.reference)
    base = class_map(args.base)
    selected = compute_closure(reference, base)
    copy_classes(selected, reference, stage)

    report = {
        "reference_class_count": len(reference),
        "base_class_count": len(base),
        "selected_class_count": len(selected),
        "selected_classes": selected,
        "source_license": "GPL-3.0-or-later",
        "source_repository": "https://git.dr2.site/penguinehis/SocksRevive-XHTTP-DEMO",
    }
    args.report.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(f"Staged {len(selected)} classes in {stage}")


if __name__ == "__main__":
    main()
